name: health_connector_toolbox
resolution: workspace
description: Privately inspect personal health data with optional SDK tools.
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  health_connector: ^3.10.0
  intl: ^0.20.3
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  health_connector_lint: ^1.2.1

flutter:
  uses-material-design: true
