name: health_connector_example
resolution: workspace
description: "Demonstrates how to use the health_connector plugin."
publish_to: 'none'

environment:
  sdk: ^3.12.0
  flutter: '>=3.44.0'

dependencies:
  flutter:
    sdk: flutter

  health_connector:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  health_connector_lint: ^1.2.1
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
