name: CD - health_connector_logger

on:
  push:
    tags:
      - 'health_connector_logger-v[0-9]+.[0-9]+.[0-9]+'
      - 'health_connector_logger-v[0-9]+.[0-9]+.[0-9]+-alpha'
      - 'health_connector_logger-v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+'
      - 'health_connector_logger-v[0-9]+.[0-9]+.[0-9]+-beta'
      - 'health_connector_logger-v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+'
      - 'health_connector_logger-v[0-9]+.[0-9]+.[0-9]+-rc'
      - 'health_connector_logger-v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+'

permissions:
  contents: read
  id-token: write

concurrency:
  group: cd-health_connector_logger-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release-validation:
    uses: ./.github/workflows/_reusable-release-validation.yaml
    with:
      package-path: packages/health_connector_logger

  dart-quality:
    needs: release-validation
    uses: ./.github/workflows/_reusable-dart-quality.yaml
    with:
      package-scope: health_connector_logger

  dart-tests:
    needs: dart-quality
    uses: ./.github/workflows/_reusable-dart-tests.yaml
    with:
      package-scope: health_connector_logger

  publish:
    needs: dart-tests
    uses: ./.github/workflows/_reusable-publish.yaml
    with:
      package-path: packages/health_connector_logger
